// Generated by Supabase MCP — do not edit manually
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_usage_logs: {
        Row: {
          created_at: string
          error_message: string | null
          estimated_cost_cents: number | null
          id: string
          input_tokens: number
          job_run_id: string | null
          latency_ms: number | null
          metadata: Json | null
          model: string
          operation_type: Database["public"]["Enums"]["ai_operation_type"]
          output_tokens: number
          provider: string
          reference_id: string | null
          reference_type: string | null
          status: string
          total_tokens: number
          user_id: string | null
          workspace_id: string
        }
        Insert: {
          created_at?: string
          error_message?: string | null
          estimated_cost_cents?: number | null
          id?: string
          input_tokens?: number
          job_run_id?: string | null
          latency_ms?: number | null
          metadata?: Json | null
          model: string
          operation_type: Database["public"]["Enums"]["ai_operation_type"]
          output_tokens?: number
          provider: string
          reference_id?: string | null
          reference_type?: string | null
          status?: string
          total_tokens?: number
          user_id?: string | null
          workspace_id: string
        }
        Update: {
          created_at?: string
          error_message?: string | null
          estimated_cost_cents?: number | null
          id?: string
          input_tokens?: number
          job_run_id?: string | null
          latency_ms?: number | null
          metadata?: Json | null
          model?: string
          operation_type?: Database["public"]["Enums"]["ai_operation_type"]
          output_tokens?: number
          provider?: string
          reference_id?: string | null
          reference_type?: string | null
          status?: string
          total_tokens?: number
          user_id?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_logs_job_run_id_fkey"
            columns: ["job_run_id"]
            isOneToOne: false
            referencedRelation: "job_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_logs_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_findings: {
        Row: {
          affected_url: string | null
          audit_id: string
          category: Database["public"]["Enums"]["finding_category"]
          created_at: string
          description: string
          evidence: Json | null
          id: string
          recommendation: string | null
          severity: Database["public"]["Enums"]["finding_severity"]
          title: string
          workspace_id: string
        }
        Insert: {
          affected_url?: string | null
          audit_id: string
          category: Database["public"]["Enums"]["finding_category"]
          created_at?: string
          description: string
          evidence?: Json | null
          id?: string
          recommendation?: string | null
          severity: Database["public"]["Enums"]["finding_severity"]
          title: string
          workspace_id: string
        }
        Update: {
          affected_url?: string | null
          audit_id?: string
          category?: Database["public"]["Enums"]["finding_category"]
          created_at?: string
          description?: string
          evidence?: Json | null
          id?: string
          recommendation?: string | null
          severity?: Database["public"]["Enums"]["finding_severity"]
          title?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_findings_audit_id_fkey"
            columns: ["audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_findings_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_reports: {
        Row: {
          ai_usage_log_id: string | null
          audit_id: string
          content_storage_path: string | null
          created_at: string
          created_by: string | null
          format: Database["public"]["Enums"]["report_format"]
          generated_by_ai: boolean
          id: string
          job_run_id: string | null
          language: string
          lead_id: string | null
          pdf_storage_path: string | null
          sent_at: string | null
          share_expires_at: string | null
          share_token: string | null
          status: Database["public"]["Enums"]["report_status"]
          summary: string | null
          title: string
          updated_at: string
          website_id: string | null
          workspace_id: string
        }
        Insert: {
          ai_usage_log_id?: string | null
          audit_id: string
          content_storage_path?: string | null
          created_at?: string
          created_by?: string | null
          format?: Database["public"]["Enums"]["report_format"]
          generated_by_ai?: boolean
          id?: string
          job_run_id?: string | null
          language?: string
          lead_id?: string | null
          pdf_storage_path?: string | null
          sent_at?: string | null
          share_expires_at?: string | null
          share_token?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          summary?: string | null
          title: string
          updated_at?: string
          website_id?: string | null
          workspace_id: string
        }
        Update: {
          ai_usage_log_id?: string | null
          audit_id?: string
          content_storage_path?: string | null
          created_at?: string
          created_by?: string | null
          format?: Database["public"]["Enums"]["report_format"]
          generated_by_ai?: boolean
          id?: string
          job_run_id?: string | null
          language?: string
          lead_id?: string | null
          pdf_storage_path?: string | null
          sent_at?: string | null
          share_expires_at?: string | null
          share_token?: string | null
          status?: Database["public"]["Enums"]["report_status"]
          summary?: string | null
          title?: string
          updated_at?: string
          website_id?: string | null
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_reports_ai_usage_log_id_fkey"
            columns: ["ai_usage_log_id"]
            isOneToOne: false
            referencedRelation: "ai_usage_logs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_reports_audit_id_fkey"
            columns: ["audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_reports_job_run_id_fkey"
            columns: ["job_run_id"]
            isOneToOne: false
            referencedRelation: "job_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_reports_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_reports_website_id_fkey"
            columns: ["website_id"]
            isOneToOne: false
            referencedRelation: "websites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_reports_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_scores: {
        Row: {
          audit_id: string
          category: Database["public"]["Enums"]["finding_category"]
          created_at: string
          id: string
          score: number
          weight: number
          workspace_id: string
        }
        Insert: {
          audit_id: string
          category: Database["public"]["Enums"]["finding_category"]
          created_at?: string
          id?: string
          score: number
          weight?: number
          workspace_id: string
        }
        Update: {
          audit_id?: string
          category?: Database["public"]["Enums"]["finding_category"]
          created_at?: string
          id?: string
          score?: number
          weight?: number
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_scores_audit_id_fkey"
            columns: ["audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_scores_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      audits: {
        Row: {
          completed_at: string | null
          created_at: string
          created_by: string | null
          duration_ms: number | null
          error_message: string | null
          id: string
          job_run_id: string | null
          lead_id: string | null
          overall_score: number | null
          pages_crawled: number | null
          score_breakdown: Json | null
          started_at: string | null
          status: Database["public"]["Enums"]["audit_status"]
          type: Database["public"]["Enums"]["audit_type"]
          updated_at: string
          website_id: string
          workspace_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          duration_ms?: number | null
          error_message?: string | null
          id?: string
          job_run_id?: string | null
          lead_id?: string | null
          overall_score?: number | null
          pages_crawled?: number | null
          score_breakdown?: Json | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["audit_status"]
          type?: Database["public"]["Enums"]["audit_type"]
          updated_at?: string
          website_id: string
          workspace_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          duration_ms?: number | null
          error_message?: string | null
          id?: string
          job_run_id?: string | null
          lead_id?: string | null
          overall_score?: number | null
          pages_crawled?: number | null
          score_breakdown?: Json | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["audit_status"]
          type?: Database["public"]["Enums"]["audit_type"]
          updated_at?: string
          website_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audits_job_run_id_fkey"
            columns: ["job_run_id"]
            isOneToOne: false
            referencedRelation: "job_runs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audits_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audits_website_id_fkey"
            columns: ["website_id"]
            isOneToOne: false
            referencedRelation: "websites"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audits_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      job_runs: {
        Row: {
          completed_at: string | null
          created_at: string
          created_by: string | null
          error_message: string | null
          id: string
          max_retries: number
          payload: Json
          priority: number
          reference_id: string | null
          reference_type: string | null
          result: Json | null
          retry_count: number
          scheduled_at: string | null
          started_at: string | null
          status: Database["public"]["Enums"]["job_status"]
          type: Database["public"]["Enums"]["job_type"]
          updated_at: string
          workspace_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          error_message?: string | null
          id?: string
          max_retries?: number
          payload?: Json
          priority?: number
          reference_id?: string | null
          reference_type?: string | null
          result?: Json | null
          retry_count?: number
          scheduled_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          type: Database["public"]["Enums"]["job_type"]
          updated_at?: string
          workspace_id: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          error_message?: string | null
          id?: string
          max_retries?: number
          payload?: Json
          priority?: number
          reference_id?: string | null
          reference_type?: string | null
          result?: Json | null
          retry_count?: number
          scheduled_at?: string | null
          started_at?: string | null
          status?: Database["public"]["Enums"]["job_status"]
          type?: Database["public"]["Enums"]["job_type"]
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "job_runs_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      lead_notes: {
        Row: {
          author_id: string
          body: string
          created_at: string
          id: string
          is_pinned: boolean
          lead_id: string
          updated_at: string
          workspace_id: string
        }
        Insert: {
          author_id: string
          body: string
          created_at?: string
          id?: string
          is_pinned?: boolean
          lead_id: string
          updated_at?: string
          workspace_id: string
        }
        Update: {
          author_id?: string
          body?: string
          created_at?: string
          id?: string
          is_pinned?: boolean
          lead_id?: string
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "lead_notes_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lead_notes_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      leads: {
        Row: {
          assigned_to: string | null
          company_name: string
          contact_email: string | null
          contact_name: string | null
          contact_phone: string | null
          created_at: string
          created_by: string | null
          deleted_at: string | null
          id: string
          industry: string | null
          last_contacted_at: string | null
          location: string | null
          metadata: Json
          notes_summary: string | null
          priority: Database["public"]["Enums"]["lead_priority"]
          score: number
          score_breakdown: Json
          source_type: Database["public"]["Enums"]["lead_source_type"]
          status: Database["public"]["Enums"]["lead_status"]
          updated_at: string
          workspace_id: string
        }
        Insert: {
          assigned_to?: string | null
          company_name: string
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          industry?: string | null
          last_contacted_at?: string | null
          location?: string | null
          metadata?: Json
          notes_summary?: string | null
          priority?: Database["public"]["Enums"]["lead_priority"]
          score?: number
          score_breakdown?: Json
          source_type?: Database["public"]["Enums"]["lead_source_type"]
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
          workspace_id: string
        }
        Update: {
          assigned_to?: string | null
          company_name?: string
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          id?: string
          industry?: string | null
          last_contacted_at?: string | null
          location?: string | null
          metadata?: Json
          notes_summary?: string | null
          priority?: Database["public"]["Enums"]["lead_priority"]
          score?: number
          score_breakdown?: Json
          source_type?: Database["public"]["Enums"]["lead_source_type"]
          status?: Database["public"]["Enums"]["lead_status"]
          updated_at?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "leads_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          full_name: string | null
          id: string
          last_active_workspace_id: string | null
          last_seen_at: string | null
          locale: string
          onboarding_completed_at: string | null
          timezone: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          full_name?: string | null
          id: string
          last_active_workspace_id?: string | null
          last_seen_at?: string | null
          locale?: string
          onboarding_completed_at?: string | null
          timezone?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          full_name?: string | null
          id?: string
          last_active_workspace_id?: string | null
          last_seen_at?: string | null
          locale?: string
          onboarding_completed_at?: string | null
          timezone?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_last_active_workspace_id_fkey"
            columns: ["last_active_workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      report_sections: {
        Row: {
          body: string
          created_at: string
          id: string
          metadata: Json | null
          order_index: number
          report_id: string
          section_type: string
          title: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          metadata?: Json | null
          order_index: number
          report_id: string
          section_type: string
          title: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          metadata?: Json | null
          order_index?: number
          report_id?: string
          section_type?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "report_sections_report_id_fkey"
            columns: ["report_id"]
            isOneToOne: false
            referencedRelation: "audit_reports"
            referencedColumns: ["id"]
          },
        ]
      }
      websites: {
        Row: {
          created_at: string
          created_by: string | null
          deleted_at: string | null
          description: string | null
          domain: string
          favicon_url: string | null
          id: string
          is_primary: boolean
          last_audit_id: string | null
          last_audited_at: string | null
          lead_id: string | null
          metadata: Json
          normalized_url: string
          status: Database["public"]["Enums"]["website_status"]
          title: string | null
          updated_at: string
          url: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          description?: string | null
          domain: string
          favicon_url?: string | null
          id?: string
          is_primary?: boolean
          last_audit_id?: string | null
          last_audited_at?: string | null
          lead_id?: string | null
          metadata?: Json
          normalized_url: string
          status?: Database["public"]["Enums"]["website_status"]
          title?: string | null
          updated_at?: string
          url: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          created_by?: string | null
          deleted_at?: string | null
          description?: string | null
          domain?: string
          favicon_url?: string | null
          id?: string
          is_primary?: boolean
          last_audit_id?: string | null
          last_audited_at?: string | null
          lead_id?: string | null
          metadata?: Json
          normalized_url?: string
          status?: Database["public"]["Enums"]["website_status"]
          title?: string | null
          updated_at?: string
          url?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "websites_last_audit_id_fkey"
            columns: ["last_audit_id"]
            isOneToOne: false
            referencedRelation: "audits"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "websites_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "websites_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspace_invites: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string
          role: Database["public"]["Enums"]["workspace_role"]
          status: Database["public"]["Enums"]["invite_status"]
          token_hash: string
          workspace_id: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at: string
          id?: string
          invited_by: string
          role?: Database["public"]["Enums"]["workspace_role"]
          status?: Database["public"]["Enums"]["invite_status"]
          token_hash: string
          workspace_id: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string
          role?: Database["public"]["Enums"]["workspace_role"]
          status?: Database["public"]["Enums"]["invite_status"]
          token_hash?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_invites_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspace_members: {
        Row: {
          created_at: string
          id: string
          invited_by: string | null
          joined_at: string | null
          role: Database["public"]["Enums"]["workspace_role"]
          status: Database["public"]["Enums"]["workspace_member_status"]
          updated_at: string
          user_id: string
          workspace_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          invited_by?: string | null
          joined_at?: string | null
          role?: Database["public"]["Enums"]["workspace_role"]
          status?: Database["public"]["Enums"]["workspace_member_status"]
          updated_at?: string
          user_id: string
          workspace_id: string
        }
        Update: {
          created_at?: string
          id?: string
          invited_by?: string | null
          joined_at?: string | null
          role?: Database["public"]["Enums"]["workspace_role"]
          status?: Database["public"]["Enums"]["workspace_member_status"]
          updated_at?: string
          user_id?: string
          workspace_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "workspace_members_workspace_id_fkey"
            columns: ["workspace_id"]
            isOneToOne: false
            referencedRelation: "workspaces"
            referencedColumns: ["id"]
          },
        ]
      }
      workspaces: {
        Row: {
          created_at: string
          created_by: string
          deleted_at: string | null
          id: string
          industry: string | null
          logo_url: string | null
          name: string
          settings: Json
          slug: string
          status: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by: string
          deleted_at?: string | null
          id?: string
          industry?: string | null
          logo_url?: string | null
          name: string
          settings?: Json
          slug: string
          status?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          deleted_at?: string | null
          id?: string
          industry?: string | null
          logo_url?: string | null
          name?: string
          settings?: Json
          slug?: string
          status?: string
          updated_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      bootstrap_user_workspace: {
        Args: { p_email: string; p_metadata?: Json; p_user_id: string }
        Returns: string
      }
      can_write_workspace: { Args: { ws_id: string }; Returns: boolean }
      ensure_user_bootstrap: { Args: { target_user_id: string }; Returns: Json }
      generate_workspace_slug: {
        Args: { base_name: string; user_id: string }
        Returns: string
      }
      has_workspace_role: {
        Args: {
          roles: Database["public"]["Enums"]["workspace_role"][]
          ws_id: string
        }
        Returns: boolean
      }
      is_workspace_member: { Args: { ws_id: string }; Returns: boolean }
    }
    Enums: {
      ai_operation_type:
        | "lead_enrichment"
        | "audit_analysis"
        | "report_generation"
        | "email_compose"
        | "reply_classification"
      audit_status: "queued" | "running" | "completed" | "failed" | "cancelled"
      audit_type: "full" | "quick" | "manual" | "scheduled"
      finding_category:
        | "performance"
        | "seo"
        | "accessibility"
        | "security"
        | "ux"
        | "content"
        | "technical"
      finding_severity: "info" | "low" | "medium" | "high" | "critical"
      invite_status: "pending" | "accepted" | "expired" | "revoked"
      job_status:
        | "pending"
        | "running"
        | "completed"
        | "failed"
        | "retrying"
        | "cancelled"
      job_type:
        | "lead_discovery"
        | "website_audit"
        | "report_generation"
        | "outreach_send"
        | "inbox_sync"
      lead_priority: "low" | "medium" | "high" | "urgent"
      lead_source_type:
        | "manual"
        | "import"
        | "discovery"
        | "referral"
        | "inbound"
      lead_status:
        | "new"
        | "enriched"
        | "qualified"
        | "contacted"
        | "replied"
        | "meeting_scheduled"
        | "won"
        | "lost"
        | "archived"
      report_format: "html" | "pdf" | "markdown"
      report_status: "draft" | "generating" | "ready" | "sent" | "failed"
      website_status: "pending" | "active" | "unreachable" | "archived"
      workspace_member_status: "active" | "invited" | "suspended" | "removed"
      workspace_role: "owner" | "admin" | "member" | "viewer"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      ai_operation_type: [
        "lead_enrichment",
        "audit_analysis",
        "report_generation",
        "email_compose",
        "reply_classification",
      ],
      audit_status: ["queued", "running", "completed", "failed", "cancelled"],
      audit_type: ["full", "quick", "manual", "scheduled"],
      finding_category: [
        "performance",
        "seo",
        "accessibility",
        "security",
        "ux",
        "content",
        "technical",
      ],
      finding_severity: ["info", "low", "medium", "high", "critical"],
      invite_status: ["pending", "accepted", "expired", "revoked"],
      job_status: [
        "pending",
        "running",
        "completed",
        "failed",
        "retrying",
        "cancelled",
      ],
      job_type: [
        "lead_discovery",
        "website_audit",
        "report_generation",
        "outreach_send",
        "inbox_sync",
      ],
      lead_priority: ["low", "medium", "high", "urgent"],
      lead_source_type: [
        "manual",
        "import",
        "discovery",
        "referral",
        "inbound",
      ],
      lead_status: [
        "new",
        "enriched",
        "qualified",
        "contacted",
        "replied",
        "meeting_scheduled",
        "won",
        "lost",
        "archived",
      ],
      report_format: ["html", "pdf", "markdown"],
      report_status: ["draft", "generating", "ready", "sent", "failed"],
      website_status: ["pending", "active", "unreachable", "archived"],
      workspace_member_status: ["active", "invited", "suspended", "removed"],
      workspace_role: ["owner", "admin", "member", "viewer"],
    },
  },
} as const
