CREATE TABLE IF NOT EXISTS lead_audits (
  id UUID PRIMARY KEY,
  lead_id UUID NOT NULL REFERENCES leads(id),
  website_url VARCHAR(500) NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS audit_issues (
  id UUID PRIMARY KEY,
  audit_id UUID NOT NULL REFERENCES lead_audits(id),
  category VARCHAR(50) NOT NULL,
  title VARCHAR(255) NOT NULL,
  severity VARCHAR(20) NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
